### ISSUE TITLE
linux release: when we build in linux release and I run it I receive the following error

### ISSUE THREAD

**Issue by vincenzopalazzo** [dart-lightning/lndart.clnapp#48]
```
➜  bundle git:(macros/releases) ✗ ./clnapp 
flutter: Error while creating AppApi
flutter: Stack trace:
 #0      _File.throwIfError (dart:io/file_impl.dart:635)
#1      _File.openSync (dart:io/file_impl.dart:479)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539)
#3      new GRPCClient (package:cln_grpc/src/cln_grpc_base.dart:65)
#4      ClientProvider._buildClient (package:clnapp/api/client_provider.dart:42)
#5      ClientProvider.getClient (package:clnapp/api/client_provider.dart:33)
#6      main.<anonymous closure> (package:clnapp/main.dart:27)
#7      _ServiceFactory.getObject (package:get_it/get_it_impl.dart:160)
#8      _GetItImplementation.get (package:get_it/get_it_impl.dart:409)
#9      AppProvider.get (package:clnapp/utils/app_provider.dart:13)
#10     _HomeViewState.getamountMsat (package:clnapp/views/home/home_view.dart:140)
#11     _HomeViewState.initState (package:clnapp/views/home/home_view.dart:35)
#12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4942)
#13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781)
#14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817)

```

To build in linux release you can do

```
flutter build linux --release
cd build/linux/x64/release/bundle/
./clnapp
```

**Comment by vincenzopalazzo** [comment]
This is also cause in the web version!
