### ISSUE TITLE
cln app do not work when we try to pay an invoice with any amount

### ISSUE THREAD

**Issue by vincenzopalazzo** [dart-lightning/lndart.clnapp#87]
Trying to pay the following invoice where the amount is any

```
lntb1pjp50d2sp58xnxem6034jdczh5hw9wpydtre6uredj5ldclsefw9tufrfg542spp5nrh4dy08u2txsshwgksw39gzmpfakkyl36gegrwnw4fdelv9h7xqdqavdkxugrpwpczqar9wd6zqurjyqur2xqyjw5qcqp2rzjqwyx8nu2hygyvgc02cwdtvuxe0lcxz06qt3lpsldzcdr46my5epmjf9c9yqqqegqqyqqqqlgqqqqqqgq9q9qxpqysgqmlg6tqn3s40rtvxtq4jvdgvd35mpgnzfaysmg3m9zy6clcrdgfg80nyx3zs4vta6m8vw5jrq4zaytey87hkh3dve3xh0adtld258vtcpk9az7y
```

So in the UI we should specify the amount but looks like the amount do not work.

Also the error handling do not work well, in the terminal I see

```
lutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   LogManager.debug (package:cln_common/src/logger/logger_manager.dart:16:13)
flutter: │ #1   UnixRPCClient.transmit.<anonymous closure> (package:clightning_rpc/src/utils/unix_rpc_client.dart:24:16)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 Event received is {"jsonrpc":"2.0","id":81767493,"error":{"code":-32602,"message":"msatoshi parameter required"}}
flutter: │ 🐛 
flutter: │ 🐛 
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'LNClientException'

```

but in the app I do not see nothings

**Comment by mdmohsin7** [comment]
When I pass some amount, I get the following error
```
{"code":-32602,"message":"unknown parameter: msatoshi, this may be caused by a failure to autodetect key=value-style parameters. Please try using the -k flag and explicit key=value pairs of parameters."}
```

**Comment by vincenzopalazzo** [comment]
yeah this is cause by the API change from core lightning, so PR are welcome to fix this

**Comment by mdmohsin7** [comment]
Can you please create a similar invoice as the one mentioned thread has expired. Would love to debug and fix this and hopefully open a PR.

**Comment by vincenzopalazzo** [comment]
Fixed in https://github.com/dart-lightning/lndart.clnapp/pull/112
